version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: git_hooks
    versions:
    - 0.6.0
    - 0.6.1
  - dependency-name: ex_aws
    versions:
    - 2.1.7
    - 2.1.9
    - 2.2.0
  - dependency-name: timex
    versions:
    - 3.6.4
    - 3.7.0
    - 3.7.2
    - 3.7.3
  - dependency-name: hackney
    versions:
    - 1.17.1
    - 1.17.2
    - 1.17.3
    - 1.17.4
  - dependency-name: phoenix
    versions:
    - 1.5.8
  - dependency-name: ex_machina
    versions:
    - 2.6.0
    - 2.7.0
  - dependency-name: phoenix_swagger
    versions:
    - 0.8.3
