language: elixir
elixir: 1.10.3
otp_release: '22.3.4'
env:
  - MIX_ENV=test
cache:
  directories:
    - _build
    - deps
    - priv/plts
before_install:
  - sudo systemctl stop 'postgresql@*.service' 'postgresql.service'
  - sudo apt-get -qqy remove '*postgresql*'
  - sudo rm -rf /etc/postgresql
  - sudo apt-get -qqy update
  - sudo apt-get -qqy install postgresql-11 postgresql-client-11
  - sudo cp ./.travis.pg_hba.conf /etc/postgresql/11/main/pg_hba.conf
  - sudo systemctl restart 'postgresql@11-main'
before_script:
  - mix ecto.setup
script:
  - mix format --check-formatted
  - mix credo
  - mix coveralls.travis
  - mix dialyzer
  - mix inch.report
branches:
  only:
    - master
