language: elixir
elixir: 1.5.0
otp_release: '20.1'
env:
  - MIX_ENV=test COMMAND="mix coveralls.travis"
  - MIX_ENV=test COMMAND="mix credo"
  - MIX_ENV=dev COMMAND="mix dialyzer --halt-exit-status"
cache:
  directories:
    - _build
    - deps
addons:
  postgresql: '9.6'
services:
  - postgresql
before_script:
  - mix ecto.setup
script:
  - $COMMAND
