language: elixir
elixir: 1.6.6
otp_release: '21.0'
env:
  - MIX_ENV=test HEX_HTTP_CONCURRENCY=1 HEX_HTTP_TIMEOUT=120
cache:
  directories:
    - _build
    - deps
addons:
  postgresql: '9.6'
services:
  - postgresql
before_install:
  - cp config/secrets.exs.example config/secrets.exs
  - rm -rf ~/.hex/packages
before_script:
  - mix ecto.setup
script:
  - mix coveralls.travis
  - mix credo
  - mix inch.report
  - mix format --check-formatted
