language: elixir
elixir: 1.5.0
otp_release: '20.1'
env:
  - MIX_ENV=test
cache:
  directories:
    - _build
    - deps
addons:
  postgresql: '9.6'
services:
  - postgresql
before_script:
  - mix ecto.setup
script:
  - mix coveralls.travis
  - mix credo
  - mix dialyzer --halt-exit-status
