language: elixir
elixir: 1.8.1
otp_release: '21.0'
env:
  - MIX_ENV=test
cache:
  directories:
    - _build
    - deps
addons:
  postgresql: '9.6'
services:
  - postgresql
before_install:
  - cp config/secrets.exs.example config/secrets.exs
before_script:
  - mix ecto.setup
script:
  - mix coveralls.travis
  - mix credo
  - mix inch.report
  - mix format --check-formatted
