# credo:disable-for-this-file Credo.Check.Readability.ModuleDoc
# @moduledoc is actually generated by a macro inside Quantum.Scheduler
defmodule Cadet.Autograder.Scheduler do
  use Quantum.Scheduler, otp_app: :cadet
end
